id: P009580
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:07.600781
source_metadata:
  id: bdr:W1KG6260
  title: 'སྤང་ལྗོངས་མེ་ཏོག་འཁྲིགས་པའི་ལྡིང་ཁང་། '
  author: ''
  volumes:
    f545a40cbe4c405daa92e256346bacff:
      image_group_id: I1KG6311
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
