id: P009580
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6260
  title: 'སྤང་ལྗོངས་མེ་ཏོག་འཁྲིགས་པའི་ལྡིང་ཁང་། '
  author: ''
  volumes:
    f545a40cbe4c405daa92e256346bacff:
      image_group_id: I1KG6311
      title: ''
      volume_number: 1
      total_pages: 300
