id: IEF444F94
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:04:04+00:00'
last_modified: '2022-06-08T12:02:15.789573+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6260
  title: 'སྤང་ལྗོངས་མེ་ཏོག་འཁྲིགས་པའི་ལྡིང་ཁང་། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    9CB2:
      image_group_id: I1KG6311
      title: ''
      total_pages: 300
      order: 1
      base_file: 9CB2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
